use_frameworks!
platform :ios, '10.3'

target 'Forms_Example' do
  pod 'Forms', :path => '../'

  target 'Forms_Tests' do
    inherit! :search_paths

#    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
